### ISSUE TITLE
Cannot read property 'configure' of undefined (utils_1.bigNumberConfigs)

### ISSUE THREAD

**Issue by BlinkyStitt** [0xProject/connect-starter-project#3]
I made a simple Dockerfile to try out https://0xproject.com/wiki#WebSocket-Tutorial:
```
# https://github.com/nodejs/docker-node/blob/df8782dfddf8c70663f0a7d19942120b1d6977a5/9/onbuild/Dockerfile
FROM node:onbuild
RUN npm run download_snapshot
```

`npm run download_snapshot`, `npm run testrpc` and `npm run api` work great, but `npm run tutorial1` and `npm run tutorial2:part1` both give this error:
```
$ npm run tutorial2:part1
npm info it worked if it ends with ok
npm info using npm@3.10.9
npm info using node@v7.1.0
npm info lifecycle 0xConnectStarterProject@0.0.0~pretutorial2:part1: 0xConnectStarterProject@0.0.0
npm info lifecycle 0xConnectStarterProject@0.0.0~tutorial2:part1: 0xConnectStarterProject@0.0.0

> 0xConnectStarterProject@0.0.0 tutorial2:part1 /usr/src/app
> npm run build; node ./lib/tutorials/websocket/generate_initial_book.js; node ./lib/tutorials/websocket/index.js

npm info it worked if it ends with ok
npm info using npm@3.10.9
npm info using node@v7.1.0
npm info lifecycle 0xConnectStarterProject@0.0.0~prebuild: 0xConnectStarterProject@0.0.0
npm info lifecycle 0xConnectStarterProject@0.0.0~build: 0xConnectStarterProject@0.0.0

> 0xConnectStarterProject@0.0.0 build /usr/src/app
> tsc

npm info lifecycle 0xConnectStarterProject@0.0.0~postbuild: 0xConnectStarterProject@0.0.0
npm info ok 
/usr/src/app/node_modules/@0xproject/connect/lib/src/index.js:5
utils_1.bigNumberConfigs.configure();
                        ^

TypeError: Cannot read property 'configure' of undefined
    at Object.<anonymous> (/usr/src/app/node_modules/@0xproject/connect/lib/src/index.js:5:25)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/src/app/lib/tutorials/websocket/generate_initial_book.js:49:17)
    at Module._compile (module.js:573:32)
/usr/src/app/node_modules/@0xproject/connect/lib/src/index.js:5
utils_1.bigNumberConfigs.configure();
                        ^

TypeError: Cannot read property 'configure' of undefined
    at Object.<anonymous> (/usr/src/app/node_modules/@0xproject/connect/lib/src/index.js:5:25)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/src/app/lib/tutorials/websocket/index.js:40:17)
    at Module._compile (module.js:573:32)

npm info lifecycle 0xConnectStarterProject@0.0.0~tutorial2:part1: Failed to exec tutorial2:part1 script
npm ERR! Linux 4.9.49-moby
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "tutorial2:part1"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! 0xConnectStarterProject@0.0.0 tutorial2:part1: `npm run build; node ./lib/tutorials/websocket/generate_initial_book.js; node ./lib/tutorials/websocket/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the 0xConnectStarterProject@0.0.0 tutorial2:part1 script 'npm run build; node ./lib/tutorials/websocket/generate_initial_book.js; node ./lib/tutorials/websocket/index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the 0xConnectStarterProject package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build; node ./lib/tutorials/websocket/generate_initial_book.js; node ./lib/tutorials/websocket/index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 0xConnectStarterProject
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 0xConnectStarterProject
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log
```

So the problem is inside `node ./lib/tutorials/websocket/generate_initial_book.js`
```
root@fe7f6f74dbf8:/usr/src/app# node ./lib/tutorials/websocket/generate_initial_book.js
/usr/src/app/node_modules/@0xproject/connect/lib/src/index.js:5
utils_1.bigNumberConfigs.configure();
                        ^

TypeError: Cannot read property 'configure' of undefined
    at Object.<anonymous> (/usr/src/app/node_modules/@0xproject/connect/lib/src/index.js:5:25)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/src/app/lib/tutorials/websocket/generate_initial_book.js:49:17)
    at Module._compile (module.js:573:32)
```

**Comment by BlinkyStitt** [comment]
`npm list` shows that we are pinned to a bugfix version of bignumber. I wonder if we need more fixes:

```
+-- bignumber.js@4.1.0
...
+-- web3@0.20.3
| +-- bignumber.js@2.0.7 (git+https://github.com/frozeman/bignumber.js-nolookahead.git#57692b3ecfc98bbdd6b3a516cb2353652ea49934)```

**Comment by BMillman19** [comment]
@WyseNynja try updating to version 0.4.1 of @0xproject/connect in the tutorial project

**Comment by BlinkyStitt** [comment]
That fixed `npm run tutorial1`. I changed package.json from `"@0xproject/connect": "^0.3.0",` to `"@0xproject/connect": "^0.4.1",` and the tutorials are working now.

The package-lock.json will also need to be updated.

Unfortunately, I get a new error on tutorial2 now:
```
npm run tutorial2:part1
npm info it worked if it ends with ok
npm info using npm@3.10.9
npm info using node@v7.1.0
npm info lifecycle 0xConnectStarterProject@0.0.0~pretutorial2:part1: 0xConnectStarterProject@0.0.0
npm info lifecycle 0xConnectStarterProject@0.0.0~tutorial2:part1: 0xConnectStarterProject@0.0.0

> 0xConnectStarterProject@0.0.0 tutorial2:part1 /usr/src/app
> npm run build; node ./lib/tutorials/websocket/generate_initial_book.js; node ./lib/tutorials/websocket/index.js

npm info it worked if it ends with ok
npm info using npm@3.10.9
npm info using node@v7.1.0
npm info lifecycle 0xConnectStarterProject@0.0.0~prebuild: 0xConnectStarterProject@0.0.0
npm info lifecycle 0xConnectStarterProject@0.0.0~build: 0xConnectStarterProject@0.0.0

> 0xConnectStarterProject@0.0.0 build /usr/src/app
> tsc

npm info lifecycle 0xConnectStarterProject@0.0.0~postbuild: 0xConnectStarterProject@0.0.0
npm info ok 
Listening for ZRX/WETH orderbook...
ERROR: Error: Expected message to conform to schema /RelayerApiOrderbookChannelSnapshot
Encountered: {
	"type": "snapshot",
	"channel": "orderbook",
	"requestId": 1,
	"payload": {
		"bids": [
			{
				"exchangeContractAddress": "0xb69e673309512a9d726f87304c6984054f87a93b",
				"maker": "0x6ecbe1db9ef729cbe972c83fb886247691fb6beb",
				"taker": "0x0000000000000000000000000000000000000000",
				"makerTokenAddress": "0x48bacb9266a570d521063ef5dd96e61686dbe788",
				"takerTokenAddress": "0x34d402f14d58e001d8efbe6585051bf9706aa064",
				"makerTokenAmount": "5000000000000000000",
				"takerTokenAmount": "50000000000000000000",
				"expirationUnixTimestampSec": "1515902559461",
				"salt": "34715315079868786009652389447367281032920004687767332350147341109447003864782",
				"feeRecipient": "0x0000000000000000000000000000000000000000",
				"makerFee": "0",
				"takerFee": "10000000000000000000",
				"ecSignature": {
					"v": 27,
					"r": "0x1ff764c0ee027c1c82661d0dd6324a5801b3290a04e4868305979346ff9ba57c",
					"s": "0x41a42a0cedd2ac00b24b22b5a46e22dfdb75d3937a238964b90d1f17e5d2917b"
				}
			},
			{
				"exchangeContractAddress": "0xb69e673309512a9d726f87304c6984054f87a93b",
				"maker": "0xe36ea790bc9d7ab70c55260c66d52b1eca985f84",
				"taker": "0x0000000000000000000000000000000000000000",
				"makerTokenAddress": "0x48bacb9266a570d521063ef5dd96e61686dbe788",
				"takerTokenAddress": "0x34d402f14d58e001d8efbe6585051bf9706aa064",
				"makerTokenAmount": "5000000000000000000",
				"takerTokenAmount": "100000000000000000000",
				"expirationUnixTimestampSec": "1515902559484",
				"salt": "35396613749948131628933738709013305547761442950077358232598071659446206669021",
				"feeRecipient": "0x0000000000000000000000000000000000000000",
				"makerFee": "0",
				"takerFee": "10000000000000000000",
				"ecSignature": {
					"v": 28,
					"r": "0xf9f3f60e8914d1e8e4d56ccee10335fcffa48f09fff8b1633403bc547912d8b1",
					"s": "0x1b3f142c82652cf0dd32a1808e1cf74fc59661eee99290dc8a689926ba32d09e"
				}
			},
			{
				"exchangeContractAddress": "0xb69e673309512a9d726f87304c6984054f87a93b",
				"maker": "0xe834ec434daba538cd1b9fe1582052b880bd7e63",
				"taker": "0x0000000000000000000000000000000000000000",
				"makerTokenAddress": "0x48bacb9266a570d521063ef5dd96e61686dbe788",
				"takerTokenAddress": "0x34d402f14d58e001d8efbe6585051bf9706aa064",
				"makerTokenAmount": "5000000000000000000",
				"takerTokenAmount": "150000000000000000000",
				"expirationUnixTimestampSec": "1515902559498",
				"salt": "49379640172186756348366120181573040648166062493294477034918978520386207417075",
				"feeRecipient": "0x0000000000000000000000000000000000000000",
				"makerFee": "0",
				"takerFee": "10000000000000000000",
				"ecSignature": {
					"v": 28,
					"r": "0xc05d9a990ca502f1d7d834de7e4bd914f853424cc7396504cecaed313abbb545",
					"s": "0x215274b8968c2c311c8e79f19b837bf348d9e4f71009bbfb1c77e990f3d11140"
				}
			},
			{
				"exchangeContractAddress": "0xb69e673309512a9d726f87304c6984054f87a93b",
				"maker": "0x78dc5d2d739606d31509c31d654056a45185ecb6",
				"taker": "0x0000000000000000000000000000000000000000",
				"makerTokenAddress": "0x48bacb9266a570d521063ef5dd96e61686dbe788",
				"takerTokenAddress": "0x34d402f14d58e001d8efbe6585051bf9706aa064",
				"makerTokenAmount": "5000000000000000000",
				"takerTokenAmount": "200000000000000000000",
				"expirationUnixTimestampSec": "1515902559514",
				"salt": "63933829572592612267892406104084830558443204088824659956014040611218087627577",
				"feeRecipient": "0x0000000000000000000000000000000000000000",
				"makerFee": "0",
				"takerFee": "10000000000000000000",
				"ecSignature": {
					"v": 28,
					"r": "0xd3f002043c5e50f6dd0725a6cc0dd6214f31979081be90fe8795261035495ade",
					"s": "0x356aeac07be523e6e0e9fc2f2d5847fbea90d6eaceaf5c52d71497d45bba1ab0"
				}
			},
			{
				"exchangeContractAddress": "0xb69e673309512a9d726f87304c6984054f87a93b",
				"maker": "0xa8dda8d7f5310e4a9e24f8eba77e091ac264f872",
				"taker": "0x0000000000000000000000000000000000000000",
				"makerTokenAddress": "0x48bacb9266a570d521063ef5dd96e61686dbe788",
				"takerTokenAddress": "0x34d402f14d58e001d8efbe6585051bf9706aa064",
				"makerTokenAmount": "5000000000000000000",
				"takerTokenAmount": "250000000000000000000",
				"expirationUnixTimestampSec": "1515902559519",
				"salt": "93728353863248054255194494648461504130397681978941738806608749558843189192881",
				"feeRecipient": "0x0000000000000000000000000000000000000000",
				"makerFee": "0",
				"takerFee": "10000000000000000000",
				"ecSignature": {
					"v": 27,
					"r": "0xa62dc61596a44ac3b9f4c28a9bc07a959584f7db91160e9eee1af3c39a38db8c",
					"s": "0x489e751deef1cc2f9c8d6dca26e4675835e54676197a4bc9f92fa565312aeb48"
				}
			},
			{
				"exchangeContractAddress": "0xb69e673309512a9d726f87304c6984054f87a93b",
				"maker": "0x06cef8e666768cc40cc78cf93d9611019ddcb628",
				"taker": "0x0000000000000000000000000000000000000000",
				"makerTokenAddress": "0x48bacb9266a570d521063ef5dd96e61686dbe788",
				"takerTokenAddress": "0x34d402f14d58e001d8efbe6585051bf9706aa064",
				"makerTokenAmount": "5000000000000000000",
				"takerTokenAmount": "300000000000000000000",
				"expirationUnixTimestampSec": "1515902559525",
				"salt": "66636703168150279813172612161578555623395015717721088794953296467487068186673",
				"feeRecipient": "0x0000000000000000000000000000000000000000",
				"makerFee": "0",
				"takerFee": "10000000000000000000",
				"ecSignature": {
					"v": 28,
					"r": "0xd198ca4f56cbb4075c8d84b927c7a0c420117ea890dffc208ad204e17f2100e9",
					"s": "0x3cf88b3b1f509701fd7f3e55fdae8869e951c5773e3dfa5177b9facde3eadc28"
				}
			},
			{
				"exchangeContractAddress": "0xb69e673309512a9d726f87304c6984054f87a93b",
				"maker": "0x4404ac8bd8f9618d27ad2f1485aa1b2cfd82482d",
				"taker": "0x0000000000000000000000000000000000000000",
				"makerTokenAddress": "0x48bacb9266a570d521063ef5dd96e61686dbe788",
				"takerTokenAddress": "0x34d402f14d58e001d8efbe6585051bf9706aa064",
				"makerTokenAmount": "5000000000000000000",
				"takerTokenAmount": "350000000000000000000",
				"expirationUnixTimestampSec": "1515902559528",
				"salt": "19695553074406614528786266062673892445060025828877875448123934138049607141328",
				"feeRecipient": "0x0000000000000000000000000000000000000000",
				"makerFee": "0",
				"takerFee": "10000000000000000000",
				"ecSignature": {
					"v": 28,
					"r": "0xeebd091d7d3ae9a7def5303d03f67d78d420918f235587d7d02768a22774ce74",
					"s": "0x0ca2dc0815c15b0e384f55fb1599f24057e41c250399b3eb13b3ec5efe8a0c25"
				}
			},
			{
				"exchangeContractAddress": "0xb69e673309512a9d726f87304c6984054f87a93b",
				"maker": "0x7457d5e02197480db681d3fdf256c7aca21bdc12",
				"taker": "0x0000000000000000000000000000000000000000",
				"makerTokenAddress": "0x48bacb9266a570d521063ef5dd96e61686dbe788",
				"takerTokenAddress": "0x34d402f14d58e001d8efbe6585051bf9706aa064",
				"makerTokenAmount": "5000000000000000000",
				"takerTokenAmount": "400000000000000000000",
				"expirationUnixTimestampSec": "1515902559532",
				"salt": "3380832662934521302249524965391244627734411486151907738960071222787904970423",
				"feeRecipient": "0x0000000000000000000000000000000000000000",
				"makerFee": "0",
				"takerFee": "10000000000000000000",
				"ecSignature": {
					"v": 27,
					"r": "0xae7687c9788ab9e1839557d7a83d3c4c33b653172359ae93eb76ebe224c40a20",
					"s": "0x0cf5375b1394d2068e0f03c362d5e7e78f566ec6de3e7b65eb2eb6c0afa14506"
				}
			},
			{
				"exchangeContractAddress": "0xb69e673309512a9d726f87304c6984054f87a93b",
				"maker": "0x91c987bf62d25945db517bdaa840a6c661374402",
				"taker": "0x0000000000000000000000000000000000000000",
				"makerTokenAddress": "0x48bacb9266a570d521063ef5dd96e61686dbe788",
				"takerTokenAddress": "0x34d402f14d58e001d8efbe6585051bf9706aa064",
				"makerTokenAmount": "5000000000000000000",
				"takerTokenAmount": "450000000000000000000",
				"expirationUnixTimestampSec": "1515902559538",
				"salt": "72777451726038875601137865164789550323208604745459737998689708454045849373864",
				"feeRecipient": "0x0000000000000000000000000000000000000000",
				"makerFee": "0",
				"takerFee": "10000000000000000000",
				"ecSignature": {
					"v": 28,
					"r": "0x92567973b44739851afd8b9587166e10027ff5614249354c02b1a0c432ebcdd3",
					"s": "0x2bbd13bf8a2c0d6999468c5b63229c3d6c261b4dd2611c94984cefdc56966da3"
				}
			}
		],
		"asks": [
			{
				"exchangeContractAddress": "0xb69e673309512a9d726f87304c6984054f87a93b",
				"maker": "0xe834ec434daba538cd1b9fe1582052b880bd7e63",
				"taker": "0x0000000000000000000000000000000000000000",
				"makerTokenAddress": "0x34d402f14d58e001d8efbe6585051bf9706aa064",
				"takerTokenAddress": "0x48bacb9266a570d521063ef5dd96e61686dbe788",
				"makerTokenAmount": "5000000000000000000",
				"takerTokenAmount": "1000000000000000000",
				"expirationUnixTimestampSec": "1515902560036",
				"salt": "45334180706424883305573954268717380737171064760979337386247841730689223654259",
				"feeRecipient": "0x0000000000000000000000000000000000000000",
				"makerFee": "0",
				"takerFee": "10000000000000000000",
				"ecSignature": {
					"v": 28,
					"r": "0x288f0845f1d66ba35312ab043d2ce00b04718e03d2fa5966ff0e3ec9bbcca972",
					"s": "0x5e033fc08435025e06980cbeb9f74982e15db48827339b5e6becff0b71fd01a7"
				}
			},
			{
				"exchangeContractAddress": "0xb69e673309512a9d726f87304c6984054f87a93b",
				"maker": "0x78dc5d2d739606d31509c31d654056a45185ecb6",
				"taker": "0x0000000000000000000000000000000000000000",
				"makerTokenAddress": "0x34d402f14d58e001d8efbe6585051bf9706aa064",
				"takerTokenAddress": "0x48bacb9266a570d521063ef5dd96e61686dbe788",
				"makerTokenAmount": "5000000000000000000",
				"takerTokenAmount": "1000000000000000000",
				"expirationUnixTimestampSec": "1515902560041",
				"salt": "3033098005036946700751637924446749691083271870696047638242387236587109199657",
				"feeRecipient": "0x0000000000000000000000000000000000000000",
				"makerFee": "0",
				"takerFee": "10000000000000000000",
				"ecSignature": {
					"v": 28,
					"r": "0xfec87aff43a42202c753188e915dec1838f301de6d1577d27fd008072cfabe0e",
					"s": "0x235d7de75cb9b6a9a245fc461f212b9c6a9e8d5c8fa9567c7e2ef63bd27e73f2"
				}
			},
			{
				"exchangeContractAddress": "0xb69e673309512a9d726f87304c6984054f87a93b",
				"maker": "0xa8dda8d7f5310e4a9e24f8eba77e091ac264f872",
				"taker": "0x0000000000000000000000000000000000000000",
				"makerTokenAddress": "0x34d402f14d58e001d8efbe6585051bf9706aa064",
				"takerTokenAddress": "0x48bacb9266a570d521063ef5dd96e61686dbe788",
				"makerTokenAmount": "5000000000000000000",
				"takerTokenAmount": "1000000000000000000",
				"expirationUnixTimestampSec": "1515902560045",
				"salt": "17748868652628164019478124885437351607058433564107789622507042381001908555665",
				"feeRecipient": "0x0000000000000000000000000000000000000000",
				"makerFee": "0",
				"takerFee": "10000000000000000000",
				"ecSignature": {
					"v": 27,
					"r": "0x82646eca9528b7b1fdf8ad080ef259ace54ef4b81f437fc48b7167962318a53c",
					"s": "0x335d3a12cc1542467d70edd7b1cf3a2e8e90a584cbcfa65ea2c729a149505dbf"
				}
			},
			{
				"exchangeContractAddress": "0xb69e673309512a9d726f87304c6984054f87a93b",
				"maker": "0x06cef8e666768cc40cc78cf93d9611019ddcb628",
				"taker": "0x0000000000000000000000000000000000000000",
				"makerTokenAddress": "0x34d402f14d58e001d8efbe6585051bf9706aa064",
				"takerTokenAddress": "0x48bacb9266a570d521063ef5dd96e61686dbe788",
				"makerTokenAmount": "5000000000000000000",
				"takerTokenAmount": "1000000000000000000",
				"expirationUnixTimestampSec": "1515902560048",
				"salt": "52092077075356374222871976846126436346858699733917467378022169846779069251286",
				"feeRecipient": "0x0000000000000000000000000000000000000000",
				"makerFee": "0",
				"takerFee": "10000000000000000000",
				"ecSignature": {
					"v": 27,
					"r": "0xdd1dcfc8632826e85a14b690b12763411d82c44ea429a1aafbf2129a8113c0ee",
					"s": "0x1f79754e8bfb84f7a1641b59a6836cd359aa5bba7c4cd32cb27901a6541f7d4e"
				}
			},
			{
				"exchangeContractAddress": "0xb69e673309512a9d726f87304c6984054f87a93b",
				"maker": "0x4404ac8bd8f9618d27ad2f1485aa1b2cfd82482d",
				"taker": "0x0000000000000000000000000000000000000000",
				"makerTokenAddress": "0x34d402f14d58e001d8efbe6585051bf9706aa064",
				"takerTokenAddress": "0x48bacb9266a570d521063ef5dd96e61686dbe788",
				"makerTokenAmount": "5000000000000000000",
				"takerTokenAmount": "1000000000000000000",
				"expirationUnixTimestampSec": "1515902560052",
				"salt": "2396503702770719305197543246744712332900877333389130484645858897732229086289",
				"feeRecipient": "0x0000000000000000000000000000000000000000",
				"makerFee": "0",
				"takerFee": "10000000000000000000",
				"ecSignature": {
					"v": 28,
					"r": "0x89b0c167d79b6bc7b319c6ddca851a994ae3ccb39fb4f6799e0565c873814038",
					"s": "0x7ea6def189065a251ce7b82070ec193fefec0f42225457f5dc09191dccedb28f"
				}
			},
			{
				"exchangeContractAddress": "0xb69e673309512a9d726f87304c6984054f87a93b",
				"maker": "0x6ecbe1db9ef729cbe972c83fb886247691fb6beb",
				"taker": "0x0000000000000000000000000000000000000000",
				"makerTokenAddress": "0x34d402f14d58e001d8efbe6585051bf9706aa064",
				"takerTokenAddress": "0x48bacb9266a570d521063ef5dd96e61686dbe788",
				"makerTokenAmount": "5000000000000000000",
				"takerTokenAmount": "1000000000000000000",
				"expirationUnixTimestampSec": "1515902560029",
				"salt": "5575229167926550191422961466620827167102032230274675248614476292698887195619",
				"feeRecipient": "0x0000000000000000000000000000000000000000",
				"makerFee": "0",
				"takerFee": "10000000000000000000",
				"ecSignature": {
					"v": 27,
					"r": "0x03af52edb1341b4c33d72208d3cb653f7a2305e73de347f3818ddeab64ec36c8",
					"s": "0x56ad81af579c49a99eefd6b243b7c9281c1fbb3af1f3758b8b8dab9f5a04cc24"
				}
			},
			{
				"exchangeContractAddress": "0xb69e673309512a9d726f87304c6984054f87a93b",
				"maker": "0xe36ea790bc9d7ab70c55260c66d52b1eca985f84",
				"taker": "0x0000000000000000000000000000000000000000",
				"makerTokenAddress": "0x34d402f14d58e001d8efbe6585051bf9706aa064",
				"takerTokenAddress": "0x48bacb9266a570d521063ef5dd96e61686dbe788",
				"makerTokenAmount": "5000000000000000000",
				"takerTokenAmount": "1000000000000000000",
				"expirationUnixTimestampSec": "1515902560032",
				"salt": "30815935393720509409275680145210050380635268130005479712188486576404280830253",
				"feeRecipient": "0x0000000000000000000000000000000000000000",
				"makerFee": "0",
				"takerFee": "10000000000000000000",
				"ecSignature": {
					"v": 27,
					"r": "0x5f3d8e781976060d0f4576d019644b4ae4b2b21b987a00dc8f37d216c020d432",
					"s": "0x416e89c358ca3937b96f4012f2b2d623b53c1b11a8e2fb705e28e78fecea09e9"
				}
			},
			{
				"exchangeContractAddress": "0xb69e673309512a9d726f87304c6984054f87a93b",
				"maker": "0x7457d5e02197480db681d3fdf256c7aca21bdc12",
				"taker": "0x0000000000000000000000000000000000000000",
				"makerTokenAddress": "0x34d402f14d58e001d8efbe6585051bf9706aa064",
				"takerTokenAddress": "0x48bacb9266a570d521063ef5dd96e61686dbe788",
				"makerTokenAmount": "5000000000000000000",
				"takerTokenAmount": "1000000000000000000",
				"expirationUnixTimestampSec": "1515902560055",
				"salt": "85398473130950091231680812968824164666450461272349902098055537458552367729929",
				"feeRecipient": "0x0000000000000000000000000000000000000000",
				"makerFee": "0",
				"takerFee": "10000000000000000000",
				"ecSignature": {
					"v": 28,
					"r": "0x4b4ad1739871d0c57c1fd61097e4e2da9cd8cf1e1011c44593c7d0b14a19467c",
					"s": "0x5fd7b976d09492895472b415af9232c57a1e3034b0019bc45754ddd33a829139"
				}
			},
			{
				"exchangeContractAddress": "0xb69e673309512a9d726f87304c6984054f87a93b",
				"maker": "0x91c987bf62d25945db517bdaa840a6c661374402",
				"taker": "0x0000000000000000000000000000000000000000",
				"makerTokenAddress": "0x34d402f14d58e001d8efbe6585051bf9706aa064",
				"takerTokenAddress": "0x48bacb9266a570d521063ef5dd96e61686dbe788",
				"makerTokenAmount": "5000000000000000000",
				"takerTokenAmount": "1000000000000000000",
				"expirationUnixTimestampSec": "1515902560061",
				"salt": "55698518379244802497049510829044992495254240736694664592691618206014105907479",
				"feeRecipient": "0x0000000000000000000000000000000000000000",
				"makerFee": "0",
				"takerFee": "10000000000000000000",
				"ecSignature": {
					"v": 27,
					"r": "0x0523efa93139e1d56c1bef0049e595a50b4bd419329f0ee3d7595fd96d2b88c1",
					"s": "0x0bab1509fc26a61666d5798a13ab1939e7fc770c30f9b0eadb751cba655240fe"
				}
			}
		]
	}
}
Validation errors: instance requires property "channelId"
```

I'm guessing this is related to the version change in 0.4.

**Comment by BMillman19** [comment]
@WyseNynja this issue should be fixed now, but looks like the `tutorial1` script is a bit flakey now, looking into it but `tutorial2:part1` and `tutorial2:part2` should be working

**Comment by BlinkyStitt** [comment]
awesome! just in time for me to do some more tinkering

**Comment by BMillman19** [comment]
@WyseNynja should be completely fixed now on the latest master, let me know if you have any other issues!

**Comment by BlinkyStitt** [comment]
Thank you!
