### ISSUE TITLE
npm run tutorial1 fails at get orderbook step

### ISSUE THREAD

**Issue by gsampathkumar** [0xProject/connect-starter-project#4]
The "npm run tutorial1" command seems to fail when trying to fill the ZRX->ETH order. Error pasted below. Please advise and let me know if there is any other info I can provide:

ZRX Before: 1000000000
WETH Before: 0
Error: VM Exception while processing transaction: invalid opcode
    at Object.InvalidResponse (/home/gautam/code/others/0x/connect-starter-project/node_modules/web3/lib/web3/errors.js:38:16)
    at /home/gautam/code/others/0x/connect-starter-project/node_modules/web3/lib/web3/requestmanager.js:86:36
    at XMLHttpRequest.request.onreadystatechange (/home/gautam/code/others/0x/connect-starter-project/node_modules/web3/lib/web3/httpprovider.js:128:7)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/gautam/code/others/0x/connect-starter-project/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/home/gautam/code/others/0x/connect-starter-project/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpResponseEnd (/home/gautam/code/others/0x/connect-starter-project/node_modules/xhr2/lib/xhr2.js:509:12)
    at IncomingMessage.<anonymous> (/home/gautam/code/others/0x/connect-starter-project/node_modules/xhr2/lib/xhr2.js:469:24)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)

**Comment by BMillman19** [comment]
@gsampathkumar should be fixed now on the latest master, let me know if you have any other problems!

**Comment by gsampathkumar** [comment]
Fixed now. Thank you @BMillman19
